config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :tickets
  resource :search, only: [:new, :show, :edit] do
    post :new
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :users
    resources :carriages
    resources :tickets
  end

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user

  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :last_station, class_name: 'RailwayStation', foreign_key: :last_station_id

  after_create :send_notification
  after_destroy :send_cancellation

  def departure_time
    self.start_station.dep_time_in(train.route)
  end

  def arrival_time
    self.start_station.arr_time_in(train.route)
  end

  def route_name
    "#{start_station.title} - #{last_station.title}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_cancellation
    TicketsMailer.cancel_ticket(self.user, self).deliver_now
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :create

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @departure_station = RailwayStation.find_by(params[:start_station_id])
    @arrival_station = RailwayStation.find_by(params[:last_station_id])
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new(
        train_id: params[:train_id],
        start_station_id: params[:start_station_id],
        last_station_id: params[:last_station_id]
    )
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to admin_ticket_path(@ticket), notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to admin_ticket_path(@ticket), notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or consticketts between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :last_station_id, :full_name, :passport_num, :user_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :create

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @departure_station = RailwayStation.find_by(params[:start_station_id])
    @arrival_station = RailwayStation.find_by(params[:last_station_id])
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new(
        train_id: params[:train_id],
        start_station_id: params[:start_station_id],
        last_station_id: params[:last_station_id]
    )
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or consticketts between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :last_station_id, :full_name, :passport_num)
  end
end

app/views/admin/tickets/_form.html.erb
<%= form_for @ticket, url: admin_tickets_path do |form| %>
    <%= render 'common/errors', resource: @ticket %>

    <%= form.hidden_field :start_station_id %>
    <%= form.hidden_field :last_station_id %>
    <%= form.hidden_field :train_id %>

    <% if user_signed_in? && current_user.admin? %>
        <div class="field">
          <%= form.label :user, "Пользователь" %>
          <%= form.collection_select :user_id, User.all, :id, :email %>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :full_name, 'ФИО' %>
      <%= form.text_field :full_name %>
    </div>

    <div class="field">
      <%= form.label :passport_num, 'Номер паспорта' %>
      <%= form.text_field :passport_num %>
    </div>

    <div class="actions">
      <%= form.submit 'Отправить' %>
    </div>
<% end %>

app/views/admin/tickets/edit.html.erb
<h1>Редактирование билета</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Назад', tickets_path %>

app/views/admin/tickets/index.html.erb
<h1>Список билетов</h1>

<table>
  <thead>
  <tr>
    <th>ФИО</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
     <tr>
       <td><%= ticket.full_name %></td>
       <td><%= link_to 'Показать', admin_ticket_path(ticket) %></td>
       <td><%= link_to 'Редактировать', edit_admin_ticket_path(ticket) %></td>
       <td><%= link_to 'Удалить', admin_ticket_path(ticket), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
     </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать билет', new_admin_ticket_path %>

app/views/admin/tickets/new.html.erb
<h1>Купить билет</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Назад', admin_tickets_path %>

app/views/admin/tickets/show.html.erb
<p>
  <strong>Пользователь:</strong>
  <%= @ticket.user.email %>
</p>
<p>
  <strong>ФИО пассажира:</strong>
  <%= @ticket.full_name %>
</p>

<p>
  <strong>Станция/время отправления:</strong>
  <%= @ticket.start_station.title %> / <%= @ticket.departure_time %>
</p>

<p>
  <strong>Станция/время отправления:</strong>
  <%= @ticket.last_station.title %> / <%= @ticket.arrival_time %>
</p>

<%= link_to 'Редактировать', edit_admin_ticket_path(@ticket) %> |
<%= link_to 'Назад', admin_tickets_path %>