config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :tickets
  resource :search, only: [:new, :show, :edit] do
    post :new
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :users
    resources :carriages
    resources :tickets
  end

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  scope :sorted, -> (sort_type) { order("number #{sort_type}") }

  validates :number, presence: true

  before_validation :set_position

  private

  def set_position
    if train.carriages.exists?
      last_num_tran = train.carriages.maximum('number')
      self.number = last_num_tran + 1
    else
      self.number = 1
    end
  end
end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :edit, :create, :update, :destroy]

  # GET /carriages
  # GET /carriages.json
  def index
    @carriages = Carriage.all
  end

  # GET /carriages/1
  # GET /carriages/1.json
  def show
  end

  # GET /carriages/new
  def new
    @train = Train.find(params[:train_id])
    @carriage = Carriage.new
  end

  # GET /carriages/1/edit
  def edit
  end

  # POST /carriages
  # POST /carriages.json
  def create
    @carriage = @train.carriages.new(carriage_params)

    respond_to do |format|
      if @carriage.save
        format.html { redirect_to admin_train_url(@train), notice: 'Carriage was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @carriage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriages/1
  # PATCH/PUT /carriages/1.json
  def update
    respond_to do |format|
      if @carriage.update(carriage_params)
        format.html { redirect_to @carriage, notice: 'Carriage was successfully updated.' }
        format.json { render :show, status: :ok, location: @carriage }
      else
        format.html { render :edit }
        format.json { render json: @carriage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriages/1
  # DELETE /carriages/1.json
  def destroy
    @carriage.destroy
    respond_to do |format|
      format.html { redirect_to carriages_url, notice: 'Carriage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or conscarriagets between actions.
  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def set_train
    @train = Train.find(params[:train_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def carriage_params
    params.require(:carriage).permit(:number, :type, :train_id, :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, :down_seats)
  end
end

app/views/admin/carriages/_coupe_carriage.html.erb
<p>
  <strong>Тип:</strong> купе
</p>
<p>
  <strong>Количество верхних мест:</strong>
  <%= @carriage.top_seats %>
</p>
<p>
  <strong>Количество нижних мест:</strong>
  <%= @carriage.bottom_seats %>
</p>

app/views/admin/carriages/_economy_carriage.html.erb
<p>
  <strong>Тип:</strong> плацкарт
</p>

<p>
  <strong>Количество верхних мест:</strong>
  <%= @carriage.top_seats %>
</p>
<p>
  <strong>Количество нижних мест:</strong>
  <%= @carriage.bottom_seats %>
</p>
<p>
  <strong>Количество верхних боковых мест:</strong>
  <%= @carriage.side_top_seats %>
</p>
<p>
  <strong>Количество нижних боковых мест:</strong>
  <%= @carriage.side_bottom_seats %>
</p>

app/views/admin/carriages/_form.html.erb
<%= form_for [@train, @carriage], url: admin_train_carriages_path do |form| %>
    <%= render 'common/errors', resource: @carriage %>

    <div class="field">
      <%= form.label :type, "Тип вагона" %>
      <%= form.select :type, [['Выбрать тип вагона', 'undefined'], ['Плацкарт', 'EconomyCarriage'], ['Купе', 'CoupeCarriage'], ['Сидячий', 'SvCarriage']], id: 'carriage_type' %>
    </div>

    <div class="field carriages coupe_carr">
      <%= form.label :top_seats, "Верхние места" %>
      <%= form.number_field :top_seats, id: :carriage_top_seats %>
    </div>

    <div class="field carriages coupe_carr">
      <%= form.label :bottom_seats, "Нижние места" %>
      <%= form.number_field :bottom_seats, id: :carriage_bottom_seats %>
    </div>

    <div class="field carriages economy_carr">
      <%= form.label :side_top_seats, "Верхние боковые места" %>
      <%= form.number_field :side_top_seats, id: :carriage_side_top_seats %>
    </div>

    <div class="field carriages economy_carr">
      <%= form.label :side_bottom_seats, "Нижние боковые места" %>
      <%= form.number_field :side_bottom_seats, id: :carriage_side_bottom_seats %>
    </div>

    <div class="field carriages sv_carr">
      <%= form.label :down_seats, "Сидячие места" %>
      <%= form.number_field :down_seats, id: :carriage_down_seats %>
    </div>

    <div class="actions">
      <%= form.submit 'Отправить' %>
    </div>
<% end %>

app/views/admin/carriages/_sv_carriage.html.erb
<p>
  <strong>Тип:</strong> сидячий
</p>
<p>
  <strong>Количество сидячих мест:</strong>
  <%= @carriage.down_seats %>
</p>

app/views/admin/carriages/edit.html.erb
<h1>Редактирование вагона</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Назад', admin_carriages_path %>

app/views/admin/carriages/index.html.erb
<h1>Список вагонов</h1>

<table class="table">
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @carriages.each do |carriage| %>
      <tr>
        <td><%= carriage.number %></td>
        <td><%= link_to 'Показать', admin_carriage_path(carriage) %></td>
        <td><%= link_to 'Редактировать', edit_admin_carriage_path(carriage) %></td>
        <td><%= link_to 'Удалить', admin_carriage_path(carriage), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/admin/carriages/new.html.erb
<h1>Добавить вагон</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Назад', admin_carriages_path %>

app/views/admin/carriages/show.html.erb
<p>
  <strong>Номер:</strong>
  <%= @carriage.number %>
</p>
<% if @carriage.type == 'CoupeCarriage' %>
    <%= render 'coupe_carriage', carriage: @carriage %>
<% elsif @carriage.type == 'EconomyCarriage' %>
    <%= render 'economy_carriage', carriage: @carriage %>
<% elsif @carriage.type == 'SvCarriage' %>
    <%= render 'sv_carriage', carriage: @carriage %>
<% end %>

<%= link_to 'Назад', admin_train_path(@carriage.train) %>