config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :tickets
  resource :search, only: [:new, :show, :edit] do
    post :new
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :users
    resources :carriages
    resources :tickets
  end

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  has_many :tickets
  has_many :carriages

  def count_carriages(kind)
    carriages_count = 0
    self.carriages.each do |carriage|
      if carriage.kind == kind
        carriages_count += 1
      end
    end
    return carriages_count
  end

  def count_seats(kind, seats_type)
    seats_count = 0
    self.carriages.each do |carriage|
      if carriage.kind == kind
        if seats_type == 'bottom_seats'
          seats_count += carriage.bottom_seats
        elsif seats_type == 'top_seats'
          seats_count += carriage.top_seats
        end
      end
    end
    return seats_count
  end

  def count_seats_ar_query(type, seats_type)
    self.carriages.where(type: type).sum(seats_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to admin_train_path(@train), notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_path, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id, :sort_flag)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="field">
    <%= form.label :current_station, "Текущая станция" %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route, "Маршрут" %>
    <%= form.collection_select :route_id, Route.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :sort_flag, "Сортировка" %>
    <%= form.select :sort_flag, [['С головы поезда', true], ['С хвоста поезда', false]] %>
  </div>

  <div class="actions">
    <%= form.submit "#{ train.new_record? ? 'Создать' : 'Изменить'}" %>
  </div>
<% end %>

app/views/admin/trains/_name_edit.html.erb
<%= form_for [:admin, train], html: { style: "display: #{ hidden ? 'none' : 'block' }" } do |form| %>
  <%= render 'common/errors', resource: train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div class="actions">
    <%= form.submit 'Изменить' %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_title_<%= train.id %>">
      <%= train.number %>
    </div>
    <%= render 'name_edit', train: train, hidden: true %>
  </td>
  <td><%= link_to 'Показать', admin_train_path(train) %></td>
  <td><%= link_to 'Переименовать', '', class: 'edit_train_title', data: { train_id: train.id } %></td>
  <td><%= link_to 'Редактировать', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Удалить', admin_train_path(train), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Показать', admin_train_path(@train) %> |
<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Список поездов</h1>

<table class="table">
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Создать поезд', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Текущая станция:</strong>
  <% if @train.current_station.present? %>
      <%= @train.current_station.title %>
  <% else %>
      Не указано
  <% end %>
</p>

<% if @train.route.present? %>
    <p>
      <strong>Поезду назначен следующий маршрут:</strong> <%= @train.route.title %></p>
<% else %>
    <p>Маршрут не назначен</p>
<% end %>

<% if @train.carriages.empty? %>
    <p>У поезда нет вагонов</p>
<% else %>
    <p><strong>Вагоны:</strong></p>
    <ul>
    <% if @train.sort_flag %>
          <% @train.carriages.sorted('ASC').each do |carriage| %>
              <li><%= link_to carriage.number, admin_carriage_path(carriage)  %></a></li>
          <% end %>
    <% else %>
          <% @train.carriages.sorted('DESC').each do |carriage| %>
              <li><%= link_to carriage.number, admin_carriage_path(carriage) %></a></li>
          <% end %>
    <% end %>
    </ul>
    <ul>
      <li>Купе: <%= @train.count_carriages('Купе') %></li>
      <li>Плацкарт: <%= @train.count_carriages('Плацкарт') %></li>
    </ul>
    <p><strong>Места купе:</strong></p>
    <ul>
      <li>Верхние: <%= @train.count_seats('Купе', 'top_seats') %></li>
      <li>Нижние: <%= @train.count_seats('Купе', 'bottom_seats')  %></li>
    </ul>
    <p><strong>Места плацкарт</strong></p>
    <ul>
      <li>Верхние: <%= @train.count_seats('Плацкарт', 'top_seats') %></li>
      <li>Нижние: <%= @train.count_seats('Плацкарт', 'bottom_seats')  %></li>
    </ul>
<% end %>

<%= link_to 'Добавить вагон', new_admin_train_carriage_path(@train) %> |
<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to 'Back', admin_trains_path %>