config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :tickets
  resource :search, only: [:new, :show, :edit] do
    post :new
  end

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end
    resources :routes
    resources :users
    resources :carriages
    resources :tickets
  end

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  scope :sorted, -> (sort_type) { order("number #{sort_type}") }

  validates :number, presence: true

  before_validation :set_position

  private

  def set_position
    if train.carriages.exists?
      last_num_tran = train.carriages.maximum('number')
      self.number = last_num_tran + 1
    else
      self.number = 1
    end
  end
end

app/models/coupe_carriage.rb
class CoupeCarriage < Carriage
  validates :top_seats, :bottom_seats, presence: true
end

app/models/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  scope :sorted, -> { joins(:railway_stations_routes).order('railway_stations_routes.position ASC').uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def update_time(route, arr_time, dep_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arr_time, departure_time: dep_time) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def arr_time_in(route)
    station_route(route).try(:arrival_time)
  end

  def dep_time_in(route)
    station_route(route).try(:departure_time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :title, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
  def self.find_train(dep_station, arr_station)
    return false if dep_station == arr_station
    check_train(dep_station) & check_train(arr_station)
  end

  def self.check_train(station_id)
    Train.joins(route: :railway_stations).where(railway_stations: { id: station_id })
  end
end

app/models/sv_carriage.rb
class SvCarriage < Carriage
  validates :down_seats, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user

  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :last_station, class_name: 'RailwayStation', foreign_key: :last_station_id

  after_create :send_notification
  after_destroy :send_cancellation

  def departure_time
    self.start_station.dep_time_in(train.route)
  end

  def arrival_time
    self.start_station.arr_time_in(train.route)
  end

  def route_name
    "#{start_station.title} - #{last_station.title}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_cancellation
    TicketsMailer.cancel_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  has_many :tickets
  has_many :carriages

  def count_carriages(kind)
    carriages_count = 0
    self.carriages.each do |carriage|
      if carriage.kind == kind
        carriages_count += 1
      end
    end
    return carriages_count
  end

  def count_seats(kind, seats_type)
    seats_count = 0
    self.carriages.each do |carriage|
      if carriage.kind == kind
        if seats_type == 'bottom_seats'
          seats_count += carriage.bottom_seats
        elsif seats_type == 'top_seats'
          seats_count += carriage.top_seats
        end
      end
    end
    return seats_count
  end

  def count_seats_ar_query(type, seats_type)
    self.carriages.where(type: type).sum(seats_type)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :trackable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_tickets_path
    else
      root_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
    @railway_stations = RailwayStation.all
    @trains = Train.all
  end

  def new
    @trains = Search.find_train(params[:departure_station], params[:arrival_station])

    if @trains.present?
      @departure_station = RailwayStation.find(params[:departure_station])
      @arrival_station = RailwayStation.find(params[:arrival_station])
      render :new
    else
      redirect_to search_path, notice: 'По вашему запросу ничего не найдено.'
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :create

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @departure_station = RailwayStation.find_by(params[:start_station_id])
    @arrival_station = RailwayStation.find_by(params[:last_station_id])
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new(
        train_id: params[:train_id],
        start_station_id: params[:start_station_id],
        last_station_id: params[:last_station_id]
    )
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or consticketts between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:train_id, :start_station_id, :last_station_id, :full_name, :passport_num)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this train from being saved:</h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuTu - Администратор</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="#">TuTu</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Поиск', search_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Билеты', tickets_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Поезда', admin_trains_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Станции', admin_railway_stations_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Маршруты', admin_routes_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Вагоны', admin_carriages_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Пользователи', admin_users_path, :class => 'nav-link' %>
          </li>
        </ul>
        <span class="navbar-text">
          <% if user_signed_in? %>
            Привет, <%= current_user.name %>! Аккаунт: <%= current_user.email %> | <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Войти', new_user_session_path %>
          <% end %>
        </span>
      </div>
    </nav>
  </header>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="row">
        <div class="container-fluid">
          <div class="col-sm-12">
            <p>&copy; 2017 Anatoly Stupin. Учебный проект в <a href="http://www.thinknetica.com/" target="_blank">онлайн-школе Thinknetica</a></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuTu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <header>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="#">TuTu</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Поиск', search_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Билеты', tickets_path, :class => 'nav-link' %>
          </li>
          <% if user_signed_in? && current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'Поезда', admin_trains_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Станции', admin_railway_stations_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Маршруты', admin_routes_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Вагоны', admin_carriages_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Пользователи', admin_users_path, :class => 'nav-link' %>
            </li>
          <% end %>
        </ul>
        <span class="navbar-text">
          <% if user_signed_in? %>
            Привет, <%= current_user.name %>! Аккаунт: <%= current_user.email %> | <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Войти', new_user_session_path %>
          <% end %>
        </span>
      </div>
    </nav>
  </header>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12">
            <p>&copy; 2017 Anatoly Stupin. Учебный проект в <a href="http://www.thinknetica.com/" target="_blank">онлайн-школе Thinknetica</a></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>